import type { GameState, OpponentState } from '@overlay/shared';

const defaultOpponent: Omit<
  OpponentState,
  'entityId' | 'playerId' | 'hero' | 'board' | 'tier' | 'eliminated' | 'turnsPlayed' | 'revives'
> = {
  turnsInGame: 0,
  totalCardsPlayed: 0,
  totalCardsDrawn: 0,
  minionsOnBoard: 0,
  minionsKilledThisTurn: 0,
  cardsDrawnThisTurn: 0,
  cardsGivenThisTurn: 0,
  cardsPlayedThisTurn: 0,
  deckSize: 30,
  combo: 0,
  bountyCards: 0,
  victories: 0,
  gameType: null,
  turnTimer: 15,
  numGameTurns: 0,
  numChoices: 0,
  deathrattlesTriggeredThisTurn: 0,
  minionsDiedThisTurn: 0,
  minionsTradedThisTurn: 0,
};

export function initialOpponentState(entityId = 0, playerId = 0): OpponentState {
  return {
    entityId,
    playerId,
    hero: { entityId: 0, cardId: '', hp: 40, armor: 0 },
    board: { minions: [] },
    tier: 1,
    eliminated: false,
    turnsPlayed: 0,
    revives: 0,
    ...defaultOpponent,
  };
}

export function initialState(): GameState {
  return {
    turn: 0,
    phase: 'lobby',
    lobbySize: 8,
    anomaly: null,
    player: {
      entityId: 0,
      playerId: 0,
      name: '',
      hero: { entityId: 0, cardId: '', hp: 40, armor: 0 },
      board: { minions: [] },
      shop: { minions: [], frozen: false, rollCost: 1 },
      hand: [],
      gold: 0,
      tier: 1,
      tierUpCost: 6,
      eliminated: false,
      pendingTriple: null,
      heroPowerUsedThisTurn: false,
      handSize: 0,
      trinketUsed: false,
      cardsPlayedThisTurn: 0,
      cardsGivenThisTurn: 0,
      deckSize: 30,
      heroPowerCardId: null,
      heroPowerCost: 1,
      turnsInGame: 0,
      minionsOnBoard: 0,
      minionsKilledThisTurn: 0,
      cardsDrawnThisTurn: 0,
      goldSpentThisTurn: 0,
      shopSize: 3,
      discoveredCardId: null,
      combo: 0,
      turnsPlayed: 0,
      revives: 0,
      bountyCards: 0,
      victories: 0,
      gameType: null,
      turnTimer: 15,
      numGameTurns: 0,
      minionsTradedThisTurn: 0,
      numChoices: 0,
      gameTurn: 1,
      deathrattlesTriggeredThisTurn: 0,
      minionsDiedThisTurn: 0,
      totalCardsPlayed: 0,
      totalCardsDrawn: 0,
      entityRegistry: new Map(),
    },
    opponents: [],
  };
}
