export { recommend } from './recommend';
export { tierCurveScore } from './heuristics/tierCurve';
export { tripleScore } from './heuristics/triple';
export { tribeSynergyScore } from './heuristics/tribeSynergy';
export { predictOpponentBoard } from './opponentPredictor';
export { enumerateBuyCandidates } from './candidates';
export type { BuyCandidate } from './candidates';
export { scoreCandidate } from './simScorer';
export type { ScoreResult } from './simScorer';
export { hillClimbPosition } from './positionHillClimb';
export type { PositionResult } from './positionHillClimb';
